CarsCURDMVCDotNetCor/Controllers/ModelsController.cs
using CarsCURDMVCDotNetCor.Data;
using CarsCURDMVCDotNetCor.Models;
using CarsCURDMVCDotNetCor.ViewForme;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace CarsCURDMVCDotNetCor.Controllers
{
    public class ModelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IToastNotification _TostrNotification;
        private readonly List<string> _ExtentionList = new List<string>() { ".jpg", ".png" };
        private readonly long _MaxlengthImage = 5048576;

        public ModelsController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _TostrNotification = toastNotification;
        }
        public async Task<IActionResult> Index()
        {
            var models = await _context.Cars.Include(c => c.MakesCompaney).Include(c => c.Category)
                .Select(c => new DisplayModel { ModelName = c.ModelName, CategoryName = c.Category.Name, MakesCompaneyName = c.MakesCompaney.Name, Price = c.Price, Year = c.Year, Image = c.Image, MotorCapacity = c.MotorCapacity, Discription = c.Discription, Id = c.Id }).ToListAsync();

            return View(models);
        }

        public async Task<IActionResult> Create()
        {
            var model = new ModelViewForm()
            {
                Categories = await _context.Categories.OrderBy(c=>c.Name).ToListAsync(),
                MakesCompaneys = await _context.MakesCompaneys.OrderBy(c=>c.Name).ToListAsync(),
                Fauls = new List<string>() { "Oil", "Gas" },
                CarsColorsList = new List<string>() { "Red", "Blue", "Black", "White" }
            };
            return View("ModelForm",model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ModelViewForm model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = await _context.Categories.ToListAsync();
                model.MakesCompaneys = await _context.MakesCompaneys.ToListAsync();
                model.Fauls = new List<string>() { "Oil", "Gas" };
                model.CarsColorsList = new List<string>() { "Red", "Blue", "Black", "White" };

                _TostrNotification.AddErrorToastMessage("SomeThing Went Wrong");
                return View("ModelForm", model);

            }
            var files = Request.Form.Files;
            if (!files.Any())
            {
                model.Categories = await _context.Categories.ToListAsync();
                model.MakesCompaneys = await _context.MakesCompaneys.ToListAsync();
                model.Fauls = new List<string>() { "Oil", "Gas" };
                model.CarsColorsList = new List<string>() { "Red", "Blue", "Black", "White" };
                ModelState.AddModelError("Image", "Please Select Image");

                _TostrNotification.AddErrorToastMessage("SomeThing Went Wrong");
                return View("ModelForm", model);
            }
            var image = files.FirstOrDefault();
            if (!_ExtentionList.Contains(Path.GetExtension(image.FileName).ToLower()))
            {
                model.Categories = await _context.Categories.ToListAsync();
                model.MakesCompaneys = await _context.MakesCompaneys.ToListAsync();
                model.Fauls = new List<string>() { "Oil", "Gas" };
                model.CarsColorsList = new List<string>() { "Red", "Blue", "Black", "White" };
                ModelState.AddModelError("Image", ".jpg , .png imahes only");

                _TostrNotification.AddErrorToastMessage("SomeThing Went Wrong");
                return View("ModelForm", model);
            }

            if (_MaxlengthImage < image.Length)
            {
                model.Categories = await _context.Categories.ToListAsync();
                model.MakesCompaneys = await _context.MakesCompaneys.ToListAsync();
                model.Fauls = new List<string>() { "Oil", "Gas" };
                model.CarsColorsList = new List<string>() { "Red", "Blue", "Black", "White" };
                ModelState.AddModelError("Image", "Image is too large");

                _TostrNotification.AddErrorToastMessage("SomeThing Went Wrong");
                return View("ModelForm", model);
            }
            using var datastream = new MemoryStream();
            await image.CopyToAsync(datastream);

            var Model = new CarModel()
            {
                ModelName = model.ModelName.Trim(),
                Year = model.Year,
                Hight = model.Hight,
                Width = model.Width,
                Tall = model.Tall,
                MotorCapacity = model.MotorCapacity,
                Faul = model.Faul,
                CategoryId = model.CategoryId,
                MakesCompaneyId = model.MakesCompaneyId,
                Image = datastream.ToArray(),
                Discription = model.Discription,
                Price = model.Price,
            };

            _context.Cars.Add(Model);
            _context.SaveChanges();

            var car = await _context.Cars.OrderBy(c => c.Id).Select(c => c.Id).LastOrDefaultAsync();

            var colors = new List<CarsColor>();
            foreach (var item in model.CarsColors)
            {
                if(item !=null)
                    colors.Add(new CarsColor() { CarModelId = car, Color = item });
            }
            _context.carsColors.AddRange(colors);

            var companey_category_test = await _context.CategoryMakesCompaney.SingleOrDefaultAsync(c=> c.MakesCompaneyId==model.MakesCompaneyId && c.CategoryId == model.CategoryId);
            if (companey_category_test == null)
            {
                var CompanyCategory = new CategoryMakesCompaney()
                {
                    CategoryId = model.CategoryId,
                    MakesCompaneyId = model.MakesCompaneyId,
                };
                _context.CategoryMakesCompaney.Add(CompanyCategory);
            }
            _context.SaveChanges();
            _TostrNotification.AddSuccessToastMessage("Model Created Successfully !");

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return BadRequest();

           ModelDetails car = await _context.Cars.Where(c => c.Id == id).Include(c=>c.Category)
                .Include(c=>c.MakesCompaney)
                .Include(c=>c.CarsColors).Select(c=> new ModelDetails
                {
                    CarsColors = (List<string>)c.CarsColors.Select(c => c.Color ),
                    CategoryName = c.Category.Name,
                    Discription = c.Discription,
                    Faul = c.Faul,
                    Hight=c.Hight,
                    Image =c.Image,
                    MakesCompaneyName= c.MakesCompaney.Name,
                    ModelName= c.ModelName,
                    MotorCapacity=c.MotorCapacity,
                    Price=c.Price,
                    Tall=c.Tall,
                    Width=c.Width,
                    Year= c.Year


                }).FirstOrDefaultAsync();
            if( car == null)
            {
                return NotFound();
            }
           
            return View(car);

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return BadRequest();

            ModelViewForm model = await _context.Cars.Select(c => new ModelViewForm 
            {
                Id = c.Id,
                CategoryId = c.CategoryId,
                Discription = c.Discription,
                Faul =c.Faul,
                Hight = c.Hight,
                Tall = c.Tall,
                Width= c.Width,
                MakesCompaneyId=c.MakesCompaneyId,
                Image =c.Image,
                ModelName=c.ModelName,
                Price =c.Price,
                MotorCapacity =c.MotorCapacity,
                Year =c.Year,
                CarsColors  = c.CarsColors.Select(c=>c.Color).ToList(),
                
            })
                .Where(c=> c.Id == id)
                .SingleOrDefaultAsync();

            model.Categories = await _context.Categories.ToListAsync();
            model.MakesCompaneys = await _context.MakesCompaneys.ToListAsync();
            model.Fauls = new List<string>() { "Oil", "Gas" };
            model.CarsColorsList = new List<string>() { "Red", "Blue", "Black", "White" };
            return View("ModelForm",model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ModelViewForm model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = await _context.Categories.ToListAsync();
                model.MakesCompaneys = await _context.MakesCompaneys.ToListAsync();
                model.Fauls = new List<string>() { "Oil", "Gas" };
                model.CarsColorsList = new List<string>() { "Red", "Blue", "Black", "White" };

                _TostrNotification.AddErrorToastMessage("SomeThing Went Wrong");
                return View("ModelForm", model);
            }
            var car = await _context.Cars.SingleOrDefaultAsync(c => c.Id== model.Id);
            if (car == null)
                return NotFound();
            var files = Request.Form.Files;
            if (files.Any())
            {
                var image = files.FirstOrDefault();
                if (!_ExtentionList.Contains(Path.GetExtension(image.FileName).ToLower()))
                {
                    model.Categories = await _context.Categories.ToListAsync();
                    model.MakesCompaneys = await _context.MakesCompaneys.ToListAsync();
                    model.Fauls = new List<string>() { "Oil", "Gas" };

CarsCURDMVCDotNetCor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarsCURDMVCDotNetCor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarsCURDMVCDotNetCor.styles.css" asp-append-version="true" />
    <link rel = "stylesheet" href="~/css/bootstrap.min.css" />
     <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
     <link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
     <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" />
     
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
               @* <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>*@

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Models" asp-action="Index">Home
                            <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="MakesCompaney" asp-action="Index">Companeys</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </div>
                            </li>
                        </ul>
            <form class="d-flex">
                    <input class="form-control me-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>*@
        </div>
    </div>
</nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarsCURDMVCDotNetCor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MakesCompaney" asp-action="Index">Companeys</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <br> <br />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap-datePicker/js/bootstrap-datepicker.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify");
</body>
</html>